from __future__ import annotations

from datetime import datetime, timedelta, timezone

LIVE_TELEMETRY_EVENTS: list[dict[str, object]] = []
ACTIVE_ATTACK_STATE: dict[str, object] = {
    "is_attack_active": False,
    "attack_type": None,
    "target_asset": None,
    "eal_spike_cr": 0.0,
    "last_reset_at": None,
}


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def append_live_telemetry_event(
    *,
    source: str,
    target_asset: str,
    event_type: str,
    severity: str,
    message: str,
    status: str,
) -> dict[str, object]:
    event = {
        "id": f"evt-{len(LIVE_TELEMETRY_EVENTS) + 1}",
        "timestamp": _utc_now_iso(),
        "source": source,
        "target_asset": target_asset,
        "event_type": event_type,
        "severity": severity,
        "message": message,
        "status": status,
    }
    LIVE_TELEMETRY_EVENTS.insert(0, event)
    LIVE_TELEMETRY_EVENTS[:] = LIVE_TELEMETRY_EVENTS[:10]
    return event


def seed_live_telemetry_events() -> list[dict[str, object]]:
    if LIVE_TELEMETRY_EVENTS:
        return LIVE_TELEMETRY_EVENTS

    now = datetime.now(timezone.utc)
    seed_events = [
        {"id": "evt-1", "timestamp": (now - timedelta(seconds=8)).strftime("%Y-%m-%dT%H:%M:%SZ"), "source": "Qualys", "target_asset": "core-pay-db-01", "event_type": "SCAN", "severity": "INFO", "message": "Routine agentless scan completed with no critical exposure drift.", "status": "SCANNED"},
        {"id": "evt-2", "timestamp": (now - timedelta(seconds=16)).strftime("%Y-%m-%dT%H:%M:%SZ"), "source": "Cloudflare WAF", "target_asset": "pay-gw-03", "event_type": "WAF_BLOCK", "severity": "INFO", "message": "Blocked SQLi probe on /checkout /pay-gw.", "status": "BLOCKED"},
        {"id": "evt-3", "timestamp": (now - timedelta(seconds=29)).strftime("%Y-%m-%dT%H:%M:%SZ"), "source": "Okta", "target_asset": "iam-sso-01", "event_type": "AUTH", "severity": "WARN", "message": "Anomalous sign-in burst detected for two privileged admin sessions.", "status": "ANOMALY_DETECTED"},
        {"id": "evt-4", "timestamp": (now - timedelta(seconds=41)).strftime("%Y-%m-%dT%H:%M:%SZ"), "source": "CrowdStrike", "target_asset": "corp-fs-02", "event_type": "EDR", "severity": "INFO", "message": "Endpoint telemetry shows no suspicious process chain on archive cluster.", "status": "SCANNED"},
        {"id": "evt-5", "timestamp": (now - timedelta(seconds=54)).strftime("%Y-%m-%dT%H:%M:%SZ"), "source": "Defender", "target_asset": "branch-pos-fleet", "event_type": "ENDPOINT", "severity": "WARN", "message": "Device posture drift flagged on 3 branch POS nodes.", "status": "ANOMALY_DETECTED"},
    ]
    LIVE_TELEMETRY_EVENTS.extend(seed_events)
    return LIVE_TELEMETRY_EVENTS


ASSET_DATABASE = [
    {
        "id": 1,
        "name": "core-pay-db-01",
        "business_unit": "Core Banking",
        "criticality": "Critical",
        "baseline_eal_lakhs": 112.0,
        "var_95_lakhs": 194.0,
        "var_95_cr": 1.94,
        "control_efficiency": 41.0,
        "telemetry_source": "Qualys QID-92044 + CrowdStrike Falcon",
        "explanation": "Core Banking DB Cluster ranks first because it is the highest-value operational database supporting fee settlement and customer ledger operations, so even a moderate loss event produces a disproportionate annualized loss. The asset still has weak MFA boundaries and incomplete control coverage on privileged access, which raises the chance of lateral movement and data theft. Its tail-risk exposure remains elevated because the spillover cost from outage, regulatory response, and customer remedy is large.",
        "technical_details": {"cve": "CVE-2024-10491", "cvss": 9.8, "port": 443, "mfa_enforced": False},
        "loss_breakdown": {"downtime_pct": 42, "breach_response_pct": 25, "regulatory_fines_pct": 21, "customer_remedy_pct": 12},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 58, "loss_mitigation_pct": 74},
        "threat_community": ["Ransomware Cartels", "Nation-State / Advanced Persistent Threat", "Supply-Chain Attackers"],
        "vendor_dependency": "Internal Core DB Cluster",
        "suggested_incident_reserve_lakh": 34.0,
        "persona_explanations": {
            "executive": "The core ledger and settlement platform carries the single largest annualized loss exposure at ₹1.12 Cr, with downtime and response costs absorbing the majority of direct impact. The case for a dedicated incident reserve is strong because a single disruption can trigger downstream operating losses and regulator-driven remediation that materially exceeds the asset's direct cost base.",
            "ciso": "FAIR-CAM coverage is uneven on this tranche, with threat resistance at 58% and loss mitigation at 74%, indicating good containment but incomplete avoidance before exploitation. RBI CSF and ISO 27001 evidence gaps remain concentrated in privileged access boundaries, making the recommended remediation SLA a 14-day control closure with weekly compensating controls.",
            "analyst": "The telemetry chain points to a privileged-access drift and unsupported legacy database path, with Qualys QID-92044 and CrowdStrike detections aligned to CVE-2024-10491 (CVSS 9.8) on port 443. The root cause is incomplete MFA enforcement for privileged roles, stale trusted connections, and delayed privilege recertification creating rapid lateral movement opportunities after initial compromise.",
        },
        "loss_params": {
            "lambda": 0.42,
            "severity": 2.8,
            "annualized_loss": 112.0,
            "p95_multiplier": 1.73,
            "p99_multiplier": 2.77,
        },
    },
    {
        "id": 2,
        "name": "pay-gw-03",
        "business_unit": "Payments",
        "criticality": "Critical",
        "baseline_eal_lakhs": 91.0,
        "var_95_lakhs": 161.0,
        "var_95_cr": 1.61,
        "control_efficiency": 54.0,
        "telemetry_source": "Cloudflare WAF + Okta Logs",
        "explanation": "Payments Gateway ranks second because it sits directly on the transaction path and therefore carries outsized exposure to fraud, settlement delay, and customer-impacting outages. Its active gaps are concentrated in segmented access and stale API session management, which increases the chance of unauthorized lateral access across the payment boundary. The exposure level remains high because a brief outage or fraud event can cascade into regulatory and remediation costs beyond the infrastructure loss itself.",
        "technical_details": {"cve": "CVE-2024-18502", "cvss": 9.6, "port": 443, "mfa_enforced": True},
        "loss_breakdown": {"downtime_pct": 38, "breach_response_pct": 27, "regulatory_fines_pct": 23, "customer_remedy_pct": 12},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 61, "loss_mitigation_pct": 77},
        "threat_community": ["Ransomware Cartels", "Supply-Chain Attackers", "Credential Abuse Brokers"],
        "vendor_dependency": "Razorpay / Visa Gateway",
        "suggested_incident_reserve_lakh": 28.0,
        "persona_explanations": {
            "executive": "The payment switch is the largest revenue-velocity risk node, with an annualized exposure near ₹0.91 Cr and direct loss dominated by transaction downtime and fraud response. A targeted reserve for incident response and settlement assurance is justified because even short outages can trigger immediate customer remedy and regulator notification actions.",
            "ciso": "FAIR-CAM shows stronger avoidance than the core ledger but still leaves notable dependency on external gateway controls and stale session management. The governance implication is a formal remediation SLA of 10 days for segmentation and API session hardening, with RBI CSF and SEBI CSCRF checks tied to real-time evidence retention.",
            "analyst": "Cloudflare WAF and Okta telemetry show middleware abuse, stale API tokens, and lifted privilege anomalies directly linked to CVE-2024-18502 (CVSS 9.6) on a public 443 service path. The primary root cause is segmented-access drift and weak token rotation, which multiplies fraud exposure and widens the monetization window for attacker tooling.",
        },
        "loss_params": {
            "lambda": 0.36,
            "severity": 2.35,
            "annualized_loss": 91.0,
            "p95_multiplier": 1.77,
            "p99_multiplier": 2.8,
        },
    },
    {
        "id": 3,
        "name": "corp-fs-02",
        "business_unit": "Corporate IT",
        "criticality": "High",
        "baseline_eal_lakhs": 64.0,
        "var_95_lakhs": 110.0,
        "var_95_cr": 1.10,
        "control_efficiency": 58.0,
        "telemetry_source": "Microsoft Defender + Splunk",
        "explanation": "Corporate File Share is the third-largest contributor because it stores a broad set of operational and financial records, which makes a breach expensive even when the asset is not transaction-critical. Its gaps are tied to incomplete backup encryption and delayed access recertification, leaving unencrypted data and stale permissions exposed. It is a medium-to-high exposure asset because regulatory and customer remedy costs can exceed the direct business interruption cost.",
        "technical_details": {"cve": "CVE-2023-44111", "cvss": 8.8, "port": 445, "mfa_enforced": True},
        "loss_breakdown": {"downtime_pct": 29, "breach_response_pct": 31, "regulatory_fines_pct": 24, "customer_remedy_pct": 16},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 56, "loss_mitigation_pct": 71},
        "threat_community": ["Data Theft Syndicates", "Insider Abuse Networks", "Supply-Chain Attackers"],
        "vendor_dependency": "AWS Ingress / Cloud Provider",
        "suggested_incident_reserve_lakh": 18.0,
        "persona_explanations": {
            "executive": "The file-share estate remains a meaningful exposure driver at ₹0.64 Cr because a single data-loss event creates both operating interruption and regulator-facing obligations. The recommended reserve covers discovery, legal review, and customer remedy while the business case for encryption and access recertification remains straightforward.",
            "ciso": "FAIR-CAM resistance is moderate at 56%, while containment remains 71%, suggesting that avoidance is weaker than mitigation and more evidence is needed for access governance. The key gap is backup encryption plus stale privilege review, which leaves ISO 27001 and RBI evidence mapping dependent on faster recertification and encryption closure beyond the current SLA.",
            "analyst": "Microsoft Defender and Splunk telemetry align with CVE-2023-44111 (CVSS 8.8) on port 445, with elevated event volumes tied to stale permission sets and non-encrypted backup surfaces. Root cause is delayed access recertification and incomplete encryption at rest, enabling information theft and slower containment after initial exploitation.",
        },
        "loss_params": {
            "lambda": 0.24,
            "severity": 1.95,
            "annualized_loss": 64.0,
            "p95_multiplier": 1.72,
            "p99_multiplier": 2.72,
        },
    },
    {
        "id": 4,
        "name": "cards-api-legacy",
        "business_unit": "Cards & Lending",
        "criticality": "High",
        "baseline_eal_lakhs": 48.0,
        "var_95_lakhs": 82.0,
        "var_95_cr": 0.82,
        "control_efficiency": 63.0,
        "telemetry_source": "Qualys Scanner & AppDynamics",
        "explanation": "Cards API (legacy) sits fourth because it is still exposed to older application vulnerabilities and narrower patch windows, which increases exploitability on internet-facing endpoints. The asset remains affected by delayed CVE remediation and incomplete endpoint hardening, even though its exposure is more concentrated than the broader corporate estate. Its overall risk is elevated because a compromise can affect both financial loss and customer trust across the cards portfolio.",
        "technical_details": {"cve": "CVE-2024-30111", "cvss": 9.4, "port": 8443, "mfa_enforced": False},
        "loss_breakdown": {"downtime_pct": 31, "breach_response_pct": 26, "regulatory_fines_pct": 28, "customer_remedy_pct": 15},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 63, "loss_mitigation_pct": 76},
        "threat_community": ["Ransomware Cartels", "Credential Abuse Brokers", "Supply-Chain Attackers"],
        "vendor_dependency": "Legacy Cards API Gateway",
        "suggested_incident_reserve_lakh": 16.0,
        "persona_explanations": {
            "executive": "The legacy cards API remains a material risk area at ₹0.48 Cr, driven by a combination of internet exposure, narrow patch windows, and customer trust erosion in a regulated product line. Because incident response and customer remedy likely dominate the direct financial hit, the reserve should cover both cyber response and cardholder remediation.",
            "ciso": "FAIR-CAM metrics are moderately resilient, with a 63% resistance rate and 76% mitigation rate, but legacy dependencies still leave evidence and vulnerability management gaps exposed. The remediation plan should prioritize CVE closure within 7 days and gating of legacy service access under RBI and SEBI control checks for network segmentation and endpoint hardening.",
            "analyst": "Qualys and AppDynamics telemetry align on CVE-2024-30111 (CVSS 9.4) on port 8443, with high exploitability across internet-facing routes and delayed patching. Root cause is legacy endpoint hardening and weak service isolation, leaving public API surfaces exposed despite partial controls and monitoring coverage.",
        },
        "loss_params": {
            "lambda": 0.19,
            "severity": 1.7,
            "annualized_loss": 48.0,
            "p95_multiplier": 1.71,
            "p99_multiplier": 2.71,
        },
    },
    {
        "id": 5,
        "name": "iam-sso-01",
        "business_unit": "Corporate IT",
        "criticality": "Medium",
        "baseline_eal_lakhs": 39.0,
        "var_95_lakhs": 66.0,
        "var_95_cr": 0.66,
        "control_efficiency": 71.0,
        "telemetry_source": "Okta Logs + Microsoft Entra",
        "explanation": "IAM / SSO Platform ranks fifth because it enables access across multiple downstream systems, which makes credential compromise disproportionately damaging even at a moderate direct asset value. The active issue is an MFA drift and stale privilege review gap, making unauthorized access easier to weaponize. Exposure is moderate-to-high because single-sign-on compromise can magnify downstream losses across both internal and external user paths.",
        "technical_details": {"cve": "CVE-2024-49009", "cvss": 8.1, "port": 443, "mfa_enforced": True},
        "loss_breakdown": {"downtime_pct": 22, "breach_response_pct": 32, "regulatory_fines_pct": 27, "customer_remedy_pct": 19},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 67, "loss_mitigation_pct": 81},
        "threat_community": ["Credential Abuse Brokers", "Insider Abuse Networks", "Nation-State / Advanced Persistent Threat"],
        "vendor_dependency": "Azure AD / SSO Provider",
        "suggested_incident_reserve_lakh": 12.0,
        "persona_explanations": {
            "executive": "IAM remains a business-critical access layer with ₹0.39 Cr in annualized exposure, even though its direct asset value is lower than transaction systems. The cost of a compromised SSO path is amplified by downstream access to critical apps, so a modest incident reserve still protects against business interruption and high-cost identity remediation.",
            "ciso": "FAIR-CAM is comparatively healthy at 67% threat resistance and 81% loss mitigation, but the real issue is control drift in MFA and privilege recertification across identity paths. Governance priorities should focus on stale access clean-up and continuous assurance under ISO 27001 and RBI identity controls with a 7-day evidence review SLA.",
            "analyst": "Okta and Entra telemetry show Credential abuse and privilege drift linked to CVE-2024-49009 (CVSS 8.1) and inconsistent MFA assertions across the 443 access path. Root cause is drift in policy enforcement and stale privileged access reviews that increase the blast radius of a single compromised identity.",
        },
        "loss_params": {
            "lambda": 0.15,
            "severity": 1.5,
            "annualized_loss": 39.0,
            "p95_multiplier": 1.69,
            "p99_multiplier": 2.67,
        },
    },
    {
        "id": 6,
        "name": "branch-pos-fleet",
        "business_unit": "Cards & Lending",
        "criticality": "Medium",
        "baseline_eal_lakhs": 28.0,
        "var_95_lakhs": 49.0,
        "var_95_cr": 0.49,
        "control_efficiency": 69.0,
        "telemetry_source": "Zscaler + CrowdStrike",
        "explanation": "Branch POS Fleet contributes less financially than the core payment surfaces, but it remains material because the device estate is spread across field operations and can be easier to exploit at scale. The main issue is patch latency and weak remote security posture, which increases risk of device takeover and payment data interception. Exposure is moderate and manageable if the fleet hardening program continues on schedule.",
        "technical_details": {"cve": "CVE-2023-48788", "cvss": 7.1, "port": 8443, "mfa_enforced": False},
        "loss_breakdown": {"downtime_pct": 34, "breach_response_pct": 21, "regulatory_fines_pct": 19, "customer_remedy_pct": 26},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 64, "loss_mitigation_pct": 75},
        "threat_community": ["Ransomware Cartels", "Credential Abuse Brokers", "Supply-Chain Attackers"],
        "vendor_dependency": "POS Device Fleet Vendor",
        "suggested_incident_reserve_lakh": 9.0,
        "persona_explanations": {
            "executive": "The POS fleet remains a moderate but manageable exposure at ₹0.28 Cr, with losses mainly driven by device downtime, customer-impacting payment interruptions, and remedy costs. The reserve requirement stays relatively small, but the operational case remains strong for on-time patching and remote hardening of the branch estate.",
            "ciso": "FAIR-CAM shows 64% resistance and 75% mitigation, which is healthy for a distributed field estate but still constrained by patch latency and remote-security posture drift. The governance objection is the SLA gap on field device patching, documented under RBI and ISO controls for endpoint hardening and secure configuration management.",
            "analyst": "Zscaler and CrowdStrike telemetry show device takeover risk and patch latency associated with CVE-2023-48788 (CVSS 7.1) on port 8443. Root cause is weak remote access posture and delayed configuration updates, leaving a broad installation base more exposed to unauthorized payment interception or downtime.",
        },
        "loss_params": {
            "lambda": 0.11,
            "severity": 1.3,
            "annualized_loss": 28.0,
            "p95_multiplier": 1.75,
            "p99_multiplier": 2.79,
        },
    },
    {
        "id": 7,
        "name": "hr-portal",
        "business_unit": "Corporate IT",
        "criticality": "Low",
        "baseline_eal_lakhs": 9.0,
        "var_95_lakhs": 15.0,
        "var_95_cr": 0.15,
        "control_efficiency": 88.0,
        "telemetry_source": "Azure AD Sign-Ins + Defender",
        "explanation": "HR Portal sits lower in the rank because it is operationally important but not directly tied to customer or payment flows. Its exposure remains limited because many controls are already in place, though identity validation and access review remain the main protection focus. The remaining exposure is low and mostly associated with user-account misuse rather than large financial outage or regulatory penalties.",
        "technical_details": {"cve": "CVE-2024-29808", "cvss": 6.5, "port": 443, "mfa_enforced": True},
        "loss_breakdown": {"downtime_pct": 19, "breach_response_pct": 28, "regulatory_fines_pct": 21, "customer_remedy_pct": 32},
        "primary_loss_breakdown": {"downtime_pct": 50, "incident_response_pct": 25},
        "secondary_loss_breakdown": {"regulatory_penalties_pct": 20, "customer_remedy_reputation_pct": 5},
        "fair_cam": {"threat_resistance_pct": 72, "loss_mitigation_pct": 83},
        "threat_community": ["Credential Abuse Brokers", "Insider Abuse Networks"],
        "vendor_dependency": "Azure AD / HR SaaS",
        "suggested_incident_reserve_lakh": 5.5,
        "persona_explanations": {
            "executive": "The HR portal is a low-cost, low-frequency risk item at ₹0.09 Cr and is not a meaningful driver of board-level exposure. The reserve requirement stays modest, and the value case for continuing identity hygiene remains operational rather than financial.",
            "ciso": "FAIR-CAM is strong here, with 72% threat resistance and 83% mitigation, indicating the main risk is user access discipline rather than structural exposure. The control objective is to maintain evidence quality for access review and identity assurance under ISO 27001 and RBI requirements without diverting heavy remediation spend.",
            "analyst": "Azure AD and Defender telemetry show a lower-risk exploitation pattern, with CVE-2024-29808 (CVSS 6.5) on port 443 and limited lateral movement indicators. Root cause is not broad system compromise but non-standard account hygiene and delayed access recertification, which still warrants attention to keep the exposure small.",
        },
        "loss_params": {
            "lambda": 0.05,
            "severity": 0.9,
            "annualized_loss": 9.0,
            "p95_multiplier": 1.67,
            "p99_multiplier": 2.67,
        },
    },
]

DIGITAL_ASSETS = ASSET_DATABASE

BASELINE_BU_EAL_LAKHS = {
    "Core Banking": 112.0,
    "Payments": 110.0,
    "Corporate IT": 110.0,
    "Cards & Lending": 112.0,
}

MITIGATION_CATALOG = {
    "mfa_privileged": {
        "id": 1,
        "name": "Enforce MFA on all privileged accounts",
        "description": "Applies to 340 privileged identities across 4 business units.",
        "default_on": True,
        "cost_lakhs": 12.0,
        "reduction_lakhs": 68.0,
        "allocation": {
            "Core Banking": 20,
            "Payments": 25,
            "Corporate IT": 30,
            "Cards & Lending": 15,
        },
    },
    "patch_cve": {
        "id": 2,
        "name": "Patch critical CVEs within 7 days",
        "description": "SLA tightened from 30 days on internet-facing assets.",
        "default_on": True,
        "cost_lakhs": 8.0,
        "reduction_lakhs": 54.0,
        "allocation": {
            "Core Banking": 15,
            "Payments": 30,
            "Corporate IT": 10,
            "Cards & Lending": 20,
        },
    },
    "upgrade_edr": {
        "id": 3,
        "name": "Upgrade EDR coverage to 100%",
        "description": "Currently 82% of endpoints covered.",
        "default_on": False,
        "cost_lakhs": 18.0,
        "reduction_lakhs": 31.0,
        "allocation": {
            "Core Banking": 5,
            "Payments": 8,
            "Corporate IT": 28,
            "Cards & Lending": 12,
        },
    },
    "segment_network": {
        "id": 4,
        "name": "Segment OT / payments network",
        "description": "Isolate payment switch VLAN from corporate LAN.",
        "default_on": False,
        "cost_lakhs": 22.0,
        "reduction_lakhs": 47.0,
        "allocation": {
            "Core Banking": 10,
            "Payments": 45,
            "Corporate IT": 5,
            "Cards & Lending": 18,
        },
    },
    "encrypt_backups": {
        "id": 5,
        "name": "Encrypt data at rest for all backups",
        "description": "Closes 3 unencrypted backup findings.",
        "default_on": True,
        "cost_lakhs": 6.0,
        "reduction_lakhs": 22.0,
        "allocation": {
            "Core Banking": 8,
            "Payments": 5,
            "Corporate IT": 35,
            "Cards & Lending": 5,
        },
    },
    "delay_remediation": {
        "id": 6,
        "name": "Push non-critical remediation by 30 days",
        "description": "Deprioritizes 22 low-severity findings.",
        "default_on": False,
        "cost_lakhs": 0.0,
        "reduction_lakhs": -8.0,
        "allocation": {
            "Core Banking": 20,
            "Payments": 20,
            "Corporate IT": 28,
            "Cards & Lending": 12,
        },
    },
}

MITIGATION_ACTIONS = [
    {
        "key": key,
        **control,
        "business_unit_impact": control["allocation"],
    }
    for key, control in MITIGATION_CATALOG.items()
]

REGULATORY_COMPLIANCE = {
    "ISO 27001": {
        "score": 82,
        "status": "Compliant with moderate gaps",
        "priority_gaps": [
            "Access review for privileged identities",
            "Encryption coverage for archival backups",
            "Evidence retention automation",
        ],
        "owners": ["Security Engineering", "Information Risk"],
    },
    "NIST CSF": {
        "score": 76,
        "status": "Partial coverage",
        "priority_gaps": [
            "Continuous monitoring and detection",
            "Threat intelligence calibration",
            "Recovery testing cadence",
        ],
        "owners": ["SOC", "Enterprise Architecture"],
    },
    "CIS Controls": {
        "score": 88,
        "status": "Strong baseline",
        "priority_gaps": [
            "MFA enforcement for admin accounts",
            "Endpoint hardening on legacy devices",
            "Application allow-list governance",
        ],
        "owners": ["Endpoint Security", "IAM"],
    },
    "RBI": {
        "score": 69,
        "status": "Needs remediation",
        "priority_gaps": [
            "Network segmentation for payment services",
            "Access logging and retention for critical paths",
            "Quarterly control validation",
        ],
        "owners": ["Banking Operations", "Cyber Risk"],
    },
    "SEBI": {
        "score": 74,
        "status": "Moderate readiness",
        "priority_gaps": [
            "Incident response drill coverage",
            "Business continuity validation",
            "Cyber risk reporting workflow",
        ],
        "owners": ["Compliance", "Risk Reporting"],
    },
}

COMPLIANCE_MATRIX = [
    {
        "id": "CTRL-MFA-01",
        "name": "Privileged Access MFA",
        "iso_27001": "A.5.17; A.8.2",
        "nist_csf": "PR.AC-1; PR.AC-7",
        "cis_v8": "6.5; 6.8",
        "rbi_csf": "Annex 1 §4.1",
        "sebi_cscrf": "A.1.5; 3.2",
        "status": "EVIDENCED",
        "coverage_pct": 88,
        "penalty_risk_cr": 0.45,
        "recommended_action": "Deploy FIDO2 passkeys via Okta to the remaining 29% privileged database accounts and enforce a 90-day access recertification policy to close RBI Annex 1 clause 4.1.",
        "policy_template_title": "RBI-Annex1-MFA-Enforcement-SOP.docx",
    },
    {
        "id": "CTRL-PATCH-02",
        "name": "Critical Patch SLA (7d)",
        "iso_27001": "A.12.6; A.8.3",
        "nist_csf": "ID.RA-1; PR.IP-12",
        "cis_v8": "7.3; 7.4",
        "rbi_csf": "Annex 2 §3.2",
        "sebi_cscrf": "A.2.4; 6.1",
        "status": "EVIDENCED",
        "coverage_pct": 91,
        "penalty_risk_cr": 0.32,
        "recommended_action": "Continue the 7-day patch SLA with automated ticket enforcement and complete the remaining legacy API backlog before the next board compliance checkpoint to preserve evidence quality.",
        "policy_template_title": "NIST-PR-IP12-Patch-Management-Policy.pdf",
    },
    {
        "id": "CTRL-BACKUP-03",
        "name": "Backup Encryption at Rest",
        "iso_27001": "A.8.24; A.8.25",
        "nist_csf": "PR.DS-1; PR.DS-5",
        "cis_v8": "3.11; 3.13",
        "rbi_csf": "Annex 1 §4.2",
        "sebi_cscrf": "A.1.6; 5.7",
        "status": "PARTIAL",
        "coverage_pct": 71,
        "penalty_risk_cr": 0.68,
        "recommended_action": "Encrypt the remaining archive backups in the corporate file share and validate key rotation records for all storage tiers so evidence is retained in a read-only, auditable format.",
        "policy_template_title": "ISO-A8-Encryption-Backup-Policy.pdf",
    },
    {
        "id": "CTRL-NET-04",
        "name": "Network Segmentation — Payments",
        "iso_27001": "A.13.1; A.13.2",
        "nist_csf": "PR.AC-5; DE.CM-1",
        "cis_v8": "12.2; 12.3",
        "rbi_csf": "Annex 1 §5.4",
        "sebi_cscrf": "A.2.3; 6.4",
        "status": "GAP",
        "coverage_pct": 54,
        "penalty_risk_cr": 1.2,
        "recommended_action": "Isolate the payment switch VLAN from the general corporate LAN with explicit ACLs, identity-based segmentation, and quarterly validation testing to close the remaining lateral-movement exposure.",
        "policy_template_title": "RBI-Annex1-Network-Segmentation-Control-SOP.docx",
    },
    {
        "id": "CTRL-EDR-05",
        "name": "Endpoint Detection & Response Coverage",
        "iso_27001": "A.8.2; A.8.15",
        "nist_csf": "DE.CM-1; DE.CM-7",
        "cis_v8": "10.2; 10.5",
        "rbi_csf": "Annex 2 §4.3",
        "sebi_cscrf": "A.3.1; 5.9",
        "status": "PARTIAL",
        "coverage_pct": 68,
        "penalty_risk_cr": 0.82,
        "recommended_action": "Extend EDR telemetry to all remote laptops and contractors, configure SOC alert triage playbooks, and verify that forensic evidence is retained for 180 days to meet audit expectations.",
        "policy_template_title": "NIST-DE-CM7-Detection-Response-Control-Playbook.pdf",
    },
    {
        "id": "CTRL-IR-06",
        "name": "Incident Response Drill Readiness",
        "iso_27001": "A.5.24; A.5.26",
        "nist_csf": "RS.RP-1; RC.RP-1",
        "cis_v8": "17.4; 17.10",
        "rbi_csf": "Annex 3 §2.5",
        "sebi_cscrf": "A.4.5; 7.1",
        "status": "GAP",
        "coverage_pct": 49,
        "penalty_risk_cr": 0.96,
        "recommended_action": "Run a production-grade cyber drill for payment and core-bank scenarios, capture evidence of containment actions, and document playbook updates to convert this control from point-in-time assurance to repeatable evidence.",
        "policy_template_title": "SEBI-Cyber-Drill-Readiness-Procedure.pdf",
    },
]

REMEDIATION_TICKETS = [
    {
        "id": "SEC-801",
        "finding": "Privileged IAM drift on core-banking-admin",
        "asset_id": "core-pay-db-01",
        "business_unit": "Core Banking",
        "eal_impact_lakh": 68.0,
        "owner": "A. Chatterjee",
        "priority": "CRITICAL",
        "status": "OPEN",
        "sla_hours_remaining": 42,
        "remediation_command": "aws iam put-role-policy --role-name core-banking-admin --policy-document file://core-bank-admin-policy.json && aws iam update-access-key --user-name admin-user --access-key-id AKIA...",
        "jira_key": "JIRA-4902",
    },
    {
        "id": "SEC-802",
        "finding": "Unsegmented payment network boundary",
        "asset_id": "pay-gw-03",
        "business_unit": "Payments",
        "eal_impact_lakh": 61.0,
        "owner": "R. Khanna",
        "priority": "HIGH",
        "status": "IN_PROGRESS",
        "sla_hours_remaining": 31,
        "remediation_command": "sudo iptables -A FORWARD -i eth0 -s 10.10.0.0/16 -j DROP && aws ec2 modify-network-interface-attribute --network-interface-id eni-123456 --source-dest-check '{\"Value\":false}'",
        "jira_key": "JIRA-4903",
    },
    {
        "id": "SEC-803",
        "finding": "Archive backups still unencrypted",
        "asset_id": "corp-fs-02",
        "business_unit": "Corporate IT",
        "eal_impact_lakh": 48.0,
        "owner": "S. Patil",
        "priority": "MEDIUM",
        "status": "OPEN",
        "sla_hours_remaining": 58,
        "remediation_command": "sudo find /mnt/archive -type f -exec gcloud kms encrypt --location global --keyring corp-backups --key backup-key --plaintext-file {} --ciphertext-file {}.enc \;",
        "jira_key": None,
    },
    {
        "id": "SEC-804",
        "finding": "Legacy cards API still exposes TLS 1.0",
        "asset_id": "cards-api-legacy",
        "business_unit": "Cards & Lending",
        "eal_impact_lakh": 22.0,
        "owner": "M. Verma",
        "priority": "HIGH",
        "status": "OPEN",
        "sla_hours_remaining": 16,
        "remediation_command": "sudo apt --only-upgrade install libstruts2 -y && sed -i 's/sslProtocol=TLSv1,TLSv1.1/TLSv1.2,TLSv1.3/' /etc/tomcat/server.xml",
        "jira_key": None,
    },
    {
        "id": "SEC-805",
        "finding": "EDR agent missing on remote endpoints",
        "asset_id": "iam-sso-01",
        "business_unit": "Corporate IT",
        "eal_impact_lakh": 19.0,
        "owner": "P. Nair",
        "priority": "LOW",
        "status": "DONE",
        "sla_hours_remaining": 0,
        "remediation_command": "curl -sSL https://deploy.example.com/edr.sh | bash && /opt/crowdstrike/falconctl -s --cid=...",
        "jira_key": "JIRA-4904",
    },
]

BASELINE_EAL_LAKHS = sum(asset["baseline_eal_lakhs"] for asset in DIGITAL_ASSETS)

__all__ = [
    "DIGITAL_ASSETS",
    "MITIGATION_ACTIONS",
    "REGULATORY_COMPLIANCE",
    "COMPLIANCE_MATRIX",
    "REMEDIATION_TICKETS",
    "BASELINE_EAL_LAKHS",
]
